# Redirect semua traffic HTTP ke HTTPS
server {
    listen 80;
    server_name domain.my.id www.domain.my.id;
    return 301 https://$host$request_uri;
}

# Konfigurasi HTTPS
server {
    listen 443 ssl;
    server_name domain.my.id www.domain.my.id;

    # Lokasi file SSL yang di-mount dari Docker Compose
    ssl_certificate /etc/nginx/ssl/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/key.pem;

    # Folder public Laravel (Sangat Penting!)
    root /var/www/html/public;
    index index.php index.html;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    client_max_body_size 50M;

    # Routing standar Laravel
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Mengoper file PHP ke container app (PHP-FPM)
    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}